name: Deploy API to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/api/**'
      - 'packages/shared/**'
      - '.github/workflows/deploy-api.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/api/**'
      - 'packages/shared/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd packages/shared && npm ci && npm run build
        cd ../api && npm ci

    - name: Build shared package
      run: |
        cd packages/shared
        npm run build

    - name: Generate Prisma client
      run: |
        cd packages/api
        npx prisma generate

    - name: Build API
      run: |
        cd packages/api
        npm run build

    - name: Create deployment package
      run: |
        cd packages/api
        mkdir -p deploy
        cp -r dist deploy/
        cp -r node_modules deploy/
        cp -r prisma deploy/
        cp package.json deploy/
        cp package-lock.json deploy/

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_API_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: packages/api/deploy

  build-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd packages/shared && npm ci
        cd ../api && npm ci

    - name: Run type check
      run: |
        cd packages/shared && npm run typecheck
        cd ../api && npm run typecheck

    - name: Generate Prisma client
      run: |
        cd packages/api
        npx prisma generate

    - name: Run tests
      run: |
        cd packages/api && npm run test

    - name: Build application
      run: |
        cd packages/shared && npm run build
        cd ../api && npm run build