name: Deploy Web App to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/web/**'
      - 'packages/shared/**'
      - '.github/workflows/deploy-web.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/web/**'
      - 'packages/shared/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd packages/shared && npm ci && npm run build
        cd ../web && npm ci

    - name: Build shared package
      run: |
        cd packages/shared
        npm run build

    - name: Build web application
      run: |
        cd packages/web
        npm run build
      env:
        VITE_API_URL: ${{ secrets.AZURE_API_URL }}

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "packages/web"
        api_location: ""
        output_location: "dist"

  build-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd packages/shared && npm ci
        cd ../web && npm ci

    - name: Run type check
      run: |
        cd packages/shared && npm run typecheck
        cd ../web && npm run typecheck

    - name: Run tests
      run: |
        cd packages/web && npm run test

    - name: Build application
      run: |
        cd packages/shared && npm run build
        cd ../web && npm run build